{
    "login": "ibx34",
    "id": 51100404,
    "node_id": "MDQ6VXNlcjUxMTAwNDA0",
    "avatar_url": "https://avatars1.githubusercontent.com/u/51100404?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ibx34",
    "html_url": "https://github.com/ibx34",
    "followers_url": "https://api.github.com/users/ibx34/followers",
    "following_url": "https://api.github.com/users/ibx34/following{/other_user}",
    "gists_url": "https://api.github.com/users/ibx34/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ibx34/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ibx34/subscriptions",
    "organizations_url": "https://api.github.com/users/ibx34/orgs",
    "repos_url": "https://api.github.com/users/ibx34/repos",
    "events_url": "https://api.github.com/users/ibx34/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ibx34/received_events",
    "type": "User",
    "site_admin": False,
    "name": "ibx34",
    "company": "\\owo/",
    "blog": "https://discord.gg/q7Uq8TbYvr",
    "location": "\\owo/",
    "email": None,
    "hireable": None,
    "bio": "I don't pay",
    "twitter_username": "ibx34",
    "public_repos": 12,
    "public_gists": 0,
    "followers": 0,
    "following": 7,
    "created_at": "2019-05-27T23:48:40Z",
    "updated_at": "2020-12-16T17:37:07Z",
    "private_gists": 3,
    "disk_usage": 8077,
    "collaborators": 0,
}
